### ISSUE TITLE
Shell Developer's Guide has confusing formatting errors

### ISSUE THREAD

**Issue by xandark** [burniouf/A2osX#133]
Throughout the guide, we see...

> IF [ <\expression\\> ]...

or...

> FUNCTION function_name
> { 
> 	\\<body\\>
> }
> 

Note the backslash characters that are in inconsistent places and next to the < >'s. When I first saw these, I was confused as to what the backslashes signify. Can they be scanned and removed to clarify the document?

**Comment by patrickbst** [comment]
The \'s that appear are in error.  When editing MarkDown files you have to use a slash in front of some characters to have them appear in text (otherwise they may get treated as markdown formatting code).  However, in some cases (inside code blocks) you dont need the \.  Since all the editing is done as a text file I sometimes dont see formatting errors like this unless i go and read the docs with a browser.  These particular errors have been corrected.  Closing this issue.  Feel free to open new ones if you catch any others.
