### ISSUE TITLE
Q: How can I help? 

### ISSUE THREAD

**Issue by cbmeeks** [burniouf/A2osX#29]
I have a small army of Apple computers.   I have many //e's (including platinum), //c's (one with 512K RAM card and Z80 CPU), //gs (one with ROM0 and one with ROM3), Laser 128, etc.

I've built several cards for the IIe on a breadboard (serial card on 65C51 and Mockingboard clone).  I have pretty good understanding of electronics and have programmed in 6502 assembly for a long time (although, I'm not an expert).

I'd be willing to offer some help if needed.

**Comment by burniouf** [comment]
Hello,

Thanx for your support.

Several levels of contribution are available:
-Testing : submit bugs, propose enhancement....
-Hardware : request for hardware support, find docs/specs for ".DRV" or "KM." writing.
-Software : additional external commands....enhancement.....
- Kernel : improve API, optimize code.....
- GUI.....
- TCP/IP....
.....

....


.....list is too long!

i suggest downloading latest medias, and make them boot against  your.....small army!
(curious about behaviour on the Laser 128!)

if you re interested in code writing, i could provide the way i'm working : i use Notepad++ and Applewin, the quickest way i found to edit/asm/run.....could write a separate detailed ".md"file if requIred.

Let me know the scope you want to handle.

Thanx again,
Rémy

**Comment by ccoffing** [comment]
Also interested in helping.  I'm coming at it from the Linux/FreeBSD/kernel/x86 assembly direction.  I have a IIe Platinum but have hardly more than glanced at it in 20 years.

My first contribution might be a `BUILDING.md`, if I can figure it out.  Unless you're already in the A2 retro scene, there's nothing here that even hints at how to get started with this project.  Throw me some hints, and I'll do my best to document how us newbies can get started.

**Comment by burniouf** [comment]
Thanx for your support and wellcome to this project!

Let me explain quickly how i work:

I use AppleWin Emulator on a Windows PC with //e Enh mode, RamWorks, Uthernet active and WINPCAP installed.
i mount The 4 A2osX volumes:
- BOOT on S6,D1
- DEV on S6,D2
- BUILD on S7,D1
- SRC on S7,D2

When AppleWin starts up, it boot from BUILD, which launch the S-C MASM Editor

I use TurtoiseSVN client to checkout the GitHub A2osX repository to my Windows HD.
Next, i use Notepad++ to "open folder as workspace" the repository. I made a custom Notepad++ color scheme for 65c02 opcodes & S-C MASM directives (optional, but very usefull to track push/pop bugs ;-)

i edit the various files within NotePad++, then  i "select All", "Copy" and "Paste" within Applewin Windows....that's why all source files are prefixed with MASM commands:
PR#3
PREFIX /A2OSX.BUILD
LOMEM $A00
INC 1
AUTO 6

and ends up with:
MAN
SAVE /A2OSX.SRC/DRV/DHGR.DRV.S.LIN
LOAD /A2OSX.SRC/DRV/DHGR.DRV.S
ASM

this will save,load & asm to/from  proper medias....

finally, there is some additional A2soX batch files : MAKEBOOT & MAKEDEV to build the 2 140k floppy disks.....

Using ADTPro, i then make "real" A2OSX.BOOT floppy to test on real hardware...

i do so, as i want A2osX to be able to build itself, i started to write the ASM command, and even a C compiler in the aim to develop for "A2osX environment", FROM "A2osX environment".....

Hope this helps....

**Comment by xandark** [comment]
I've often thought about this reply and that the build process that it describes seems like it requires too much manual work ("then i "select All", "Copy" and "Paste" within Applewin Windows") or it is tied to specific editors (Notepad++), emulators (AppleWin), and host operating systems (Windows). It makes it seem that the build pipeline is too narrow.

I sincerely feel that the project would get more support if the build process were more neutral towards the contributor's environment and makes things 100% automated using standard Unix makefile build tools.

By contrasti, looking at the the project for the disassembly of the [Apple II Desktop](https://github.com/inexorabletash/a2d), it appears to be more friendly to outside developers without seeming too unfamiliar.

I hope this doesn't sound like a critique, because I'm on your side and I want to see people participate in this awesome project if they have the initial desire to do so.

**Comment by xandark** [comment]
Very interesting! Yes, they are doing great work, and I bet there is a lot of overlap between what they uncovered and what you created based on what A2osX needs, like memory, device, and event managers. 

One thing that I'm not clear about is which assembler does A2osX use?

**Comment by burniouf** [comment]
A2osX is built using S-C Macro Assembler 3.0, because i use this assembler for.....35 years now!
And i like the syntax, specially the directives starting with a dot.
Embedded assembler (ASM cmd line) is based on this dialect but is table driven, allowing assembling for virtually any type of CPU. For now ASM is still lacking macro support to be completed.
The goal is to allow A2osX to assemble itself, and to assemble out of the C compiler.

**Comment by xandark** [comment]
Okay fair enough. So can others use S-C Macro Assembler 3.0? If so, I'd like to see instructions to that in A2osX's build instructions. 

I'm not familiar with ASM cmd line. Is this a Unix tool?

Very interesting the goal of self-hosting.

**Comment by burniouf** [comment]
See : http://www.txbobsc.com/scsc/
You'll find links to a bunch of documentation about it.

see above how to boot to A2OSX.BUILD media and use it.
i guess this procedure can be extended to other platforms/editors than Windows/Notepad++

**Comment by patrickbst** [comment]
@cbmeeks @ccoffing @xandark I was just wondering if you all were still willing to contribute/help with A2osX?  Have you downloaded the latest version and tested it on your various machines?  Are any of you Assembly developers?  How can we help you contribute?

**Comment by ccoffing** [comment]
@patrickbst I'm still interested, and your comment prompted me to boot A2osX on AppleWin this weekend.  I also managed to assemble a file.  I need to learn S-C Asm and figure out my own workflow to get it onto real hardware.  Then I'll try one of the bugs you've filed.

**Comment by patrickbst** [comment]
@ccoffing Chuck, thanks for the reply.  Be sure to check out the new Docs found in the .Docs directory.  The Developers Guide discusses our current Development workflow (how you edit, asm, test).  It also mentions are upcoming workflow where you will be able to ASM right in a2osx.  Good news on that front too, we are currently testing/debugging that module.  FYI we have a slack channel where we do a lot of chatting about what we are doing at the moment, we would be happy to send you invite (or if you know slack our slack name is A2OSX.  -Patrick

**Comment by patrickbst** [comment]
A new "How You Can Help" section has been added to README (copying some of what was discussed here).  As this question has been answered (AND YES we still welcome your help!), closing this issue.
