### ISSUE TITLE
lsdev crashes to monitor on .91

### ISSUE THREAD

**Issue by a2retro** [burniouf/A2osX#36]
Enhanced IIe with RWIII, Uthernet II, Floppy Disk Controller and CFFA 3000 - after boot of stock image running lsdev crashes to monitor at adder $FF6F after printing a few lines which scroll and then the screen switches back to where i ran the command.

**Comment by burniouf** [comment]
For block devices, LSDEV does basically a SMARTPORT status call with STATUS.CODE=3 to get the device DIB. 

for A2osX NIC, SSC...etc...drivers it calls the STATUS entry point....
so i need to know which driver makes LSDEV crash...
if SMARTPORT related the bug is within kernel
if other driver, the bug is in the .DRV.

**Comment by burniouf** [comment]
Fixed in 0.92, please check, then close this issue.

**Comment by patrickbst** [comment]
Confirmed that last several hundred builds run LSDEV without issue.  Closing.
