### ISSUE TITLE
A2OSX.BOOT.po file size

### ISSUE THREAD

**Issue by davidrimshnick** [burniouf/A2osX#44]
Hi - I'm trying to use A2 Floppy EMU to load `A2OSX.BOOT.po` to my IIe, but the file is not appearing in the list of available 5.25 disks.  I think it may be because the file size is only 54kb, as opposed to the 140k it is expecting.  Do I need to expand the file or something? (the file I am using is from the `.FLOPPIES` folder).

Thanks!

**Comment by patrickbst** [comment]
David, I just checked the file here on github and it shows as 140K.  Perhaps your download got interrupted?

**Comment by davidrimshnick** [comment]
Thanks Patrick; sorry for the delayed reply, was traveling for the holidays.  Seems like it had to do with the way I was downloading from github; I was right clicking and selecting "Save Link as".  Needed to click the link and then select "Download"!  Sorry for the trouble and appreciate the help!

**Comment by davidrimshnick** [comment]
Thanks Patrick!  I was able to get a2osx to boot, now trying to figure out how to get it to recognize my Uthernet 2.  Will come over to the slack channel.  Thanks again!

**Comment by patrickbst** [comment]
David (and anyone else) you can use the following link for the next 30 days to join the A2osX Slack channel: https://join.slack.com/t/a2osx/shared_invite/enQtNTEyMzcxNTcyMTY0LTRiOGE5MmIyMzE3ODAxNGI1MjcyMmViZmEzMGRiMTM5YWY1ZThjZGQ2OTFlN2FiOTA1ZDI0NWIxN2E3ODU2YTM

**Comment by patrickbst** [comment]
David, I was glad to here you were able to boot now.  To test your u2 card type the following at the prompt:
INSDRV UTHERNET2.DRV 00:08:AA:55:44:33
STARTPROC TCPIPD
DHCPCLNT
And that point you should be connected to the internet.  You can try:
PING -4 yahoo.com
TELNET a80sappleiibbs.ddns.net 6502
Note the above is if you use DHCP.  If you use fixed IP, let me know on slack and I will guide you through that.  Also once you are on slack, say Hi, and we will walk you through putting the above into a script so you dont have to rtype it everytime :)

I am going to close this issue (since the original issue is closed).  Feel free to open a new one here or on slack if you need anything else.
Patrick
